version: '3.8'
networks:
  expense:
    driver: bridge
volumes:
  db_data:
  backend_data:
  frontend_data:
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_DATABASE: expensedb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expense
  backend:
    image: backend
    container_name: backend
    restart: unless-stopped 
    volumes:
      - backend_data:/var/lib/mysql
    networks:
      - expense
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql 
      - DB_PORT=3306
      - DB_NAME=expensedb
      - DB_USER=root
      - DB_PASSWORD=ExpenseApp@1
  frontend:
    image: frontend
    container_name: frontend
    restart: unless-stopped
    volumes:
      - frontend_data:/usr/share/nginx/html
    networks: 
      - expense
    ports:
      - "80:80"
    depends_on:
      - backend
    
    