version: '3.8'
networks:
  expense:
    driver: bridge
volumes:
  db_data:
  backend_data:
  frontend_data:
services:
  mysql:
    image: expense-mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_DATABASE: transactions
      MYSQL_USER: expense
      MYSQL_PASSWORD: ExpenseApp@1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expense
  backend:
    image: expense-backend
    container_name: backend
    restart: unless-stopped 
    volumes:
      - backend_data:/opt/backend
    networks:
      - expense
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    image: expense-frontend
    container_name: frontend
    restart: unless-stopped
    volumes:
      - frontend_data:/usr/share/nginx/html
    networks: 
      - expense
    ports:
      - "80:80"
    depends_on:
      - backend
    
    